In [20]:
import pandas as pd

df = pd.read_csv('buffer-all.tsv', sep='\t')
df = df.set_index('ts')
df.index = pd.to_datetime(df.index)

display(df)
df.describe()

,conn_count_uid_in,conn_count_uid_internal,conn_count_uid_out,conn_mean_duration_in,conn_mean_duration_internal,conn_mean_duration_out,conn_nunique_uid_in,conn_nunique_uid_internal,conn_nunique_uid_out,conn_sum_orig_bytes_in,...,ssh_count_uid_in,ssh_count_uid_internal,ssh_nunique_uid_in,ssh_nunique_uid_internal,ssl_count_uid_in,ssl_count_uid_internal,ssl_count_uid_out,ssl_nunique_uid_in,ssl_nunique_uid_internal,ssl_nunique_uid_out
ts,,,,,,,,,,,,,,,,,,,,,
2021-03-11 10:40:00,11353.0,2736.0,2526.0,8.031479,0.409721,1.236616,11353.0,2736.0,2526.0,3.396384e+10,...,420.0,NaN,420.0,NaN,548.0,NaN,41.0,548.0,NaN,41.0
2021-03-11 10:50:00,11632.0,3043.0,1967.0,11.094625,0.379838,2.233771,11632.0,3043.0,1967.0,4.279624e+10,...,610.0,NaN,610.0,NaN,424.0,198.0,42.0,424.0,198.0,42.0
2021-03-11 11:00:00,9488.0,2396.0,1826.0,36.346664,0.432246,1.787685,9488.0,2396.0,1826.0,3.624221e+10,...,452.0,NaN,452.0,NaN,385.0,5.0,85.0,385.0,5.0,85.0
2021-03-11 11:10:00,12695.0,2543.0,2124.0,19.632174,0.354461,1.584054,12695.0,2543.0,2124.0,2.875885e+10,...,581.0,NaN,581.0,NaN,430.0,NaN,44.0,430.0,NaN,44.0
2021-03-11 11:20:00,10564.0,2881.0,2447.0,38.015033,0.453129,1.905568,10564.0,2881.0,2447.0,2.664415e+06,...,459.0,2.0,459.0,2.0,408.0,NaN,114.0,408.0,NaN,114.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-21 19:10:00,16977.0,1971.0,1583.0,4.223263,0.591874,5.944390,16977.0,1971.0,1583.0,1.662652e+09,...,940.0,NaN,940.0,NaN,334.0,5.0,111.0,334.0,5.0,111.0
2021-03-21 19:20:00,15615.0,2612.0,1701.0,3.215720,0.486241,5.995442,15615.0,2612.0,1701.0,2.269588e+09,...,962.0,NaN,962.0,NaN,325.0,3.0,102.0,325.0,3.0,102.0
2021-03-21 19:30:00,16063.0,2510.0,1888.0,3.691383,0.478530,5.068089,16063.0,2510.0,1888.0,7.751223e+09,...,666.0,NaN,666.0,NaN,268.0,3.0,110.0,268.0,3.0,110.0
2021-03-21 19:40:00,15493.0,2520.0,1776.0,4.937027,0.463571,6.113427,15493.0,2520.0,1776.0,1.239374e+10,...,709.0,NaN,709.0,NaN,209.0,5.0,96.0,209.0,5.0,96.0
2021-03-21 19:50:00,18009.0,2628.0,1527.0,11.949971,0.480214,6.320429,18009.0,2628.0,1527.0,2.162962e+10,...,679.0,NaN,679.0,NaN,243.0,202.0,111.0,243.0,202.0,111.0

,conn_count_uid_in,conn_count_uid_internal,conn_count_uid_out,conn_mean_duration_in,conn_mean_duration_internal,conn_mean_duration_out,conn_nunique_uid_in,conn_nunique_uid_internal,conn_nunique_uid_out,conn_sum_orig_bytes_in,...,ssh_count_uid_in,ssh_count_uid_internal,ssh_nunique_uid_in,ssh_nunique_uid_internal,ssl_count_uid_in,ssl_count_uid_internal,ssl_count_uid_out,ssl_nunique_uid_in,ssl_nunique_uid_internal,ssl_nunique_uid_out
count,1496.000000,1496.000000,1496.000000,1496.000000,1496.000000,1496.000000,1496.000000,1496.000000,1496.000000,1.496000e+03,...,1496.000000,105.000000,1496.000000,105.000000,1496.000000,1037.000000,1496.000000,1496.000000,1037.000000,1496.000000
mean,18501.440508,2690.570187,2093.904412,15.192869,2.607721,5.669973,18501.440508,2690.570187,2093.904412,1.540167e+10,...,1171.457219,2.800000,1171.457219,2.800000,304.459893,34.847637,80.185829,304.459893,34.847637,80.185829
std,5550.125028,462.993523,704.946708,43.567498,27.193994,49.127851,5550.125028,462.993523,704.946708,2.022910e+10,...,1116.347440,5.060024,1116.347440,5.060024,75.651390,65.758831,227.051890,75.651390,65.758831,227.051890
min,8162.000000,1614.000000,803.000000,0.921414,0.245235,0.645129,8162.000000,1614.000000,803.000000,1.544676e+06,...,174.000000,1.000000,174.000000,1.000000,150.000000,1.000000,6.000000,150.000000,1.000000,6.000000
25%,15084.250000,2438.750000,1683.000000,3.045963,0.355018,2.792805,15084.250000,2438.750000,1683.000000,2.984571e+09,...,602.000000,1.000000,602.000000,1.000000,249.000000,3.000000,40.000000,249.000000,3.000000,40.000000
50%,16707.000000,2655.000000,1930.500000,5.411160,0.449153,3.748613,16707.000000,2655.000000,1930.500000,9.030070e+09,...,722.500000,1.000000,722.500000,1.000000,295.000000,4.000000,49.000000,295.000000,4.000000,49.000000
75%,20301.250000,2854.250000,2279.000000,12.633516,0.535332,4.799755,20301.250000,2854.250000,2279.000000,1.931825e+10,...,1321.250000,2.000000,1321.250000,2.000000,335.000000,11.000000,100.000000,335.000000,11.000000,100.000000
max,41313.000000,4991.000000,8785.000000,732.541367,607.703839,1849.666737,41313.000000,4991.000000,8785.000000,1.725226e+11,...,12397.000000,42.000000,12397.000000,42.000000,809.000000,261.000000,6625.000000,809.000000,261.000000,6625.000000